name: tarantula-app
services:
  postoffice:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: postoffice
    hostname: postoffice
    image: ${PREFIX}/tarantula.postoffice:${VERSION}
    ports:
      - "7946:7946/tcp"
      - "7946:7946/udp"
      - "7001:7001"
      - "8080:8080"
    networks:
      - tarantula-app-net
    volumes:
      - volume_postoffice:/home/tarantula/postoffice
    env_file:
      - .env
  cloud:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: cloud
   
    hostname: cloud
    image: ${PREFIX}/tarantula.cloud:${VERSION}
    volumes:
      - volume_cloud:/home/tarantula/cloud
    depends_on:
      - postoffice
         
    networks:
      - tarantula-app-net
    env_file:
      - .env 
  admin:
    stop_grace_period: 20s
    restart: unless-stopped
    container_name: admin
   
    hostname: admin
    image: ${PREFIX}/tarantula.admin:${VERSION}
    volumes:
      - volume_admin:/home/tarantula/admin  
    depends_on:
      - cloud

    networks:
      - tarantula-app-net
    env_file:
      - .env  
  web:
    restart: unless-stopped
    container_name: web
    hostname: web
    image: ${PREFIX}/tarantula.caddy:${VERSION}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - admin
    networks:
      - tarantula-app-net
    volumes:
      - volume_caddy:/data
    env_file:
      - .env

networks:
  tarantula-app-net:
    external: true
volumes:
  volume_postoffice:
  volume_cloud:
  volume_admin:
  volume_caddy:
