// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: aws_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AwsAccess struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=accessKeyId,proto3" json:"accessKeyId,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secretAccessKey,proto3" json:"secretAccessKey,omitempty"`
	Region          string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Prefix          string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Type            string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	User            string                 `protobuf:"bytes,6,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AwsAccess) Reset() {
	*x = AwsAccess{}
	mi := &file_aws_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AwsAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AwsAccess) ProtoMessage() {}

func (x *AwsAccess) ProtoReflect() protoreflect.Message {
	mi := &file_aws_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AwsAccess.ProtoReflect.Descriptor instead.
func (*AwsAccess) Descriptor() ([]byte, []int) {
	return file_aws_access_proto_rawDescGZIP(), []int{0}
}

func (x *AwsAccess) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *AwsAccess) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *AwsAccess) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AwsAccess) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AwsAccess) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AwsAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_aws_access_proto protoreflect.FileDescriptor

const file_aws_access_proto_rawDesc = "" +
	"\n" +
	"\x10aws_access.proto\x12\bprotocol\"\xaf\x01\n" +
	"\tAwsAccess\x12 \n" +
	"\vaccessKeyId\x18\x01 \x01(\tR\vaccessKeyId\x12(\n" +
	"\x0fsecretAccessKey\x18\x02 \x01(\tR\x0fsecretAccessKey\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04user\x18\x06 \x01(\tR\x04userBQ\n" +
	"\x17com.icodesoftware.protoB\x10AwsAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_aws_access_proto_rawDescOnce sync.Once
	file_aws_access_proto_rawDescData []byte
)

func file_aws_access_proto_rawDescGZIP() []byte {
	file_aws_access_proto_rawDescOnce.Do(func() {
		file_aws_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aws_access_proto_rawDesc), len(file_aws_access_proto_rawDesc)))
	})
	return file_aws_access_proto_rawDescData
}

var file_aws_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_aws_access_proto_goTypes = []any{
	(*AwsAccess)(nil), // 0: protocol.AwsAccess
}
var file_aws_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aws_access_proto_init() }
func file_aws_access_proto_init() {
	if File_aws_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aws_access_proto_rawDesc), len(file_aws_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aws_access_proto_goTypes,
		DependencyIndexes: file_aws_access_proto_depIdxs,
		MessageInfos:      file_aws_access_proto_msgTypes,
	}.Build()
	File_aws_access_proto = out.File
	file_aws_access_proto_goTypes = nil
	file_aws_access_proto_depIdxs = nil
}
