// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: az_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AzAccess struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenantId,proto3" json:"tenantId,omitempty"`
	ClientId       string                 `protobuf:"bytes,2,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ClientSecret   string                 `protobuf:"bytes,3,opt,name=clientSecret,proto3" json:"clientSecret,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,4,opt,name=subscriptionId,proto3" json:"subscriptionId,omitempty"`
	ResourceGroup  string                 `protobuf:"bytes,5,opt,name=resourceGroup,proto3" json:"resourceGroup,omitempty"`
	Region         string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	Prefix         string                 `protobuf:"bytes,7,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Type           string                 `protobuf:"bytes,8,opt,name=type,proto3" json:"type,omitempty"`
	User           string                 `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AzAccess) Reset() {
	*x = AzAccess{}
	mi := &file_az_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AzAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AzAccess) ProtoMessage() {}

func (x *AzAccess) ProtoReflect() protoreflect.Message {
	mi := &file_az_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AzAccess.ProtoReflect.Descriptor instead.
func (*AzAccess) Descriptor() ([]byte, []int) {
	return file_az_access_proto_rawDescGZIP(), []int{0}
}

func (x *AzAccess) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AzAccess) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AzAccess) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *AzAccess) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *AzAccess) GetResourceGroup() string {
	if x != nil {
		return x.ResourceGroup
	}
	return ""
}

func (x *AzAccess) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *AzAccess) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *AzAccess) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AzAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_az_access_proto protoreflect.FileDescriptor

const file_az_access_proto_rawDesc = "" +
	"\n" +
	"\x0faz_access.proto\x12\bprotocol\"\x8c\x02\n" +
	"\bAzAccess\x12\x1a\n" +
	"\btenantId\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\bclientId\x18\x02 \x01(\tR\bclientId\x12\"\n" +
	"\fclientSecret\x18\x03 \x01(\tR\fclientSecret\x12&\n" +
	"\x0esubscriptionId\x18\x04 \x01(\tR\x0esubscriptionId\x12$\n" +
	"\rresourceGroup\x18\x05 \x01(\tR\rresourceGroup\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x16\n" +
	"\x06prefix\x18\a \x01(\tR\x06prefix\x12\x12\n" +
	"\x04type\x18\b \x01(\tR\x04type\x12\x12\n" +
	"\x04user\x18\t \x01(\tR\x04userBP\n" +
	"\x17com.icodesoftware.protoB\x0fAzAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_az_access_proto_rawDescOnce sync.Once
	file_az_access_proto_rawDescData []byte
)

func file_az_access_proto_rawDescGZIP() []byte {
	file_az_access_proto_rawDescOnce.Do(func() {
		file_az_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_az_access_proto_rawDesc), len(file_az_access_proto_rawDesc)))
	})
	return file_az_access_proto_rawDescData
}

var file_az_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_az_access_proto_goTypes = []any{
	(*AzAccess)(nil), // 0: protocol.AzAccess
}
var file_az_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_az_access_proto_init() }
func file_az_access_proto_init() {
	if File_az_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_az_access_proto_rawDesc), len(file_az_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_az_access_proto_goTypes,
		DependencyIndexes: file_az_access_proto_depIdxs,
		MessageInfos:      file_az_access_proto_msgTypes,
	}.Build()
	File_az_access_proto = out.File
	file_az_access_proto_goTypes = nil
	file_az_access_proto_depIdxs = nil
}
