// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: docker_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DockerAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        string                 `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DockerAccess) Reset() {
	*x = DockerAccess{}
	mi := &file_docker_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DockerAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DockerAccess) ProtoMessage() {}

func (x *DockerAccess) ProtoReflect() protoreflect.Message {
	mi := &file_docker_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DockerAccess.ProtoReflect.Descriptor instead.
func (*DockerAccess) Descriptor() ([]byte, []int) {
	return file_docker_access_proto_rawDescGZIP(), []int{0}
}

func (x *DockerAccess) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *DockerAccess) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DockerAccess) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DockerAccess) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *DockerAccess) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_docker_access_proto protoreflect.FileDescriptor

const file_docker_access_proto_rawDesc = "" +
	"\n" +
	"\x13docker_access.proto\x12\bprotocol\"\x8a\x01\n" +
	"\fDockerAccess\x12\x16\n" +
	"\x06server\x18\x01 \x01(\tR\x06server\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05tokenBT\n" +
	"\x17com.icodesoftware.protoB\x13DockerAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_docker_access_proto_rawDescOnce sync.Once
	file_docker_access_proto_rawDescData []byte
)

func file_docker_access_proto_rawDescGZIP() []byte {
	file_docker_access_proto_rawDescOnce.Do(func() {
		file_docker_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docker_access_proto_rawDesc), len(file_docker_access_proto_rawDesc)))
	})
	return file_docker_access_proto_rawDescData
}

var file_docker_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_docker_access_proto_goTypes = []any{
	(*DockerAccess)(nil), // 0: protocol.DockerAccess
}
var file_docker_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docker_access_proto_init() }
func file_docker_access_proto_init() {
	if File_docker_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docker_access_proto_rawDesc), len(file_docker_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docker_access_proto_goTypes,
		DependencyIndexes: file_docker_access_proto_depIdxs,
		MessageInfos:      file_docker_access_proto_msgTypes,
	}.Build()
	File_docker_access_proto = out.File
	file_docker_access_proto_goTypes = nil
	file_docker_access_proto_depIdxs = nil
}
