// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: plan_object.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlanObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vendor        string                 `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"` // gcp, aws, az
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`       // dev, stg, test, prod
	AppRepo       *RepoObject            `protobuf:"bytes,3,opt,name=appRepo,proto3" json:"appRepo,omitempty"`
	DeployRepo    *RepoObject            `protobuf:"bytes,4,opt,name=deployRepo,proto3" json:"deployRepo,omitempty"`
	TestRepo      *RepoObject            `protobuf:"bytes,5,opt,name=testRepo,proto3" json:"testRepo,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"` // service subdirectory under vendor in deploy repo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanObject) Reset() {
	*x = PlanObject{}
	mi := &file_plan_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanObject) ProtoMessage() {}

func (x *PlanObject) ProtoReflect() protoreflect.Message {
	mi := &file_plan_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanObject.ProtoReflect.Descriptor instead.
func (*PlanObject) Descriptor() ([]byte, []int) {
	return file_plan_object_proto_rawDescGZIP(), []int{0}
}

func (x *PlanObject) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *PlanObject) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *PlanObject) GetAppRepo() *RepoObject {
	if x != nil {
		return x.AppRepo
	}
	return nil
}

func (x *PlanObject) GetDeployRepo() *RepoObject {
	if x != nil {
		return x.DeployRepo
	}
	return nil
}

func (x *PlanObject) GetTestRepo() *RepoObject {
	if x != nil {
		return x.TestRepo
	}
	return nil
}

func (x *PlanObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_plan_object_proto protoreflect.FileDescriptor

const file_plan_object_proto_rawDesc = "" +
	"\n" +
	"\x11plan_object.proto\x12\bprotocol\x1a\x11repo_object.proto\"\xe2\x01\n" +
	"\n" +
	"PlanObject\x12\x16\n" +
	"\x06vendor\x18\x01 \x01(\tR\x06vendor\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12.\n" +
	"\aappRepo\x18\x03 \x01(\v2\x14.protocol.RepoObjectR\aappRepo\x124\n" +
	"\n" +
	"deployRepo\x18\x04 \x01(\v2\x14.protocol.RepoObjectR\n" +
	"deployRepo\x120\n" +
	"\btestRepo\x18\x05 \x01(\v2\x14.protocol.RepoObjectR\btestRepo\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04nameBR\n" +
	"\x17com.icodesoftware.protoB\x11PlanObjectFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_plan_object_proto_rawDescOnce sync.Once
	file_plan_object_proto_rawDescData []byte
)

func file_plan_object_proto_rawDescGZIP() []byte {
	file_plan_object_proto_rawDescOnce.Do(func() {
		file_plan_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plan_object_proto_rawDesc), len(file_plan_object_proto_rawDesc)))
	})
	return file_plan_object_proto_rawDescData
}

var file_plan_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_plan_object_proto_goTypes = []any{
	(*PlanObject)(nil), // 0: protocol.PlanObject
	(*RepoObject)(nil), // 1: protocol.RepoObject
}
var file_plan_object_proto_depIdxs = []int32{
	1, // 0: protocol.PlanObject.appRepo:type_name -> protocol.RepoObject
	1, // 1: protocol.PlanObject.deployRepo:type_name -> protocol.RepoObject
	1, // 2: protocol.PlanObject.testRepo:type_name -> protocol.RepoObject
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plan_object_proto_init() }
func file_plan_object_proto_init() {
	if File_plan_object_proto != nil {
		return
	}
	file_repo_object_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plan_object_proto_rawDesc), len(file_plan_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plan_object_proto_goTypes,
		DependencyIndexes: file_plan_object_proto_depIdxs,
		MessageInfos:      file_plan_object_proto_msgTypes,
	}.Build()
	File_plan_object_proto = out.File
	file_plan_object_proto_goTypes = nil
	file_plan_object_proto_depIdxs = nil
}
