// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: redis_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedisAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisAccess) Reset() {
	*x = RedisAccess{}
	mi := &file_redis_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisAccess) ProtoMessage() {}

func (x *RedisAccess) ProtoReflect() protoreflect.Message {
	mi := &file_redis_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisAccess.ProtoReflect.Descriptor instead.
func (*RedisAccess) Descriptor() ([]byte, []int) {
	return file_redis_access_proto_rawDescGZIP(), []int{0}
}

func (x *RedisAccess) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RedisAccess) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *RedisAccess) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_redis_access_proto protoreflect.FileDescriptor

const file_redis_access_proto_rawDesc = "" +
	"\n" +
	"\x12redis_access.proto\x12\bprotocol\"Q\n" +
	"\vRedisAccess\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpasswordBS\n" +
	"\x17com.icodesoftware.protoB\x12RedisAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_redis_access_proto_rawDescOnce sync.Once
	file_redis_access_proto_rawDescData []byte
)

func file_redis_access_proto_rawDescGZIP() []byte {
	file_redis_access_proto_rawDescOnce.Do(func() {
		file_redis_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redis_access_proto_rawDesc), len(file_redis_access_proto_rawDesc)))
	})
	return file_redis_access_proto_rawDescData
}

var file_redis_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_redis_access_proto_goTypes = []any{
	(*RedisAccess)(nil), // 0: protocol.RedisAccess
}
var file_redis_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redis_access_proto_init() }
func file_redis_access_proto_init() {
	if File_redis_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redis_access_proto_rawDesc), len(file_redis_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redis_access_proto_goTypes,
		DependencyIndexes: file_redis_access_proto_depIdxs,
		MessageInfos:      file_redis_access_proto_msgTypes,
	}.Build()
	File_redis_access_proto = out.File
	file_redis_access_proto_goTypes = nil
	file_redis_access_proto_depIdxs = nil
}
