// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: ring_sync.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RingSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Remote        string                 `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	Ranges        []*RingRange           `protobuf:"bytes,2,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingSync) Reset() {
	*x = RingSync{}
	mi := &file_ring_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingSync) ProtoMessage() {}

func (x *RingSync) ProtoReflect() protoreflect.Message {
	mi := &file_ring_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingSync.ProtoReflect.Descriptor instead.
func (*RingSync) Descriptor() ([]byte, []int) {
	return file_ring_sync_proto_rawDescGZIP(), []int{0}
}

func (x *RingSync) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *RingSync) GetRanges() []*RingRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

var File_ring_sync_proto protoreflect.FileDescriptor

const file_ring_sync_proto_rawDesc = "" +
	"\n" +
	"\x0fring_sync.proto\x12\bprotocol\x1a\x10ring_range.proto\"O\n" +
	"\bRingSync\x12\x16\n" +
	"\x06remote\x18\x01 \x01(\tR\x06remote\x12+\n" +
	"\x06ranges\x18\x02 \x03(\v2\x13.protocol.RingRangeR\x06rangesBP\n" +
	"\x17com.icodesoftware.protoB\x0fRingSyncFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_ring_sync_proto_rawDescOnce sync.Once
	file_ring_sync_proto_rawDescData []byte
)

func file_ring_sync_proto_rawDescGZIP() []byte {
	file_ring_sync_proto_rawDescOnce.Do(func() {
		file_ring_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ring_sync_proto_rawDesc), len(file_ring_sync_proto_rawDesc)))
	})
	return file_ring_sync_proto_rawDescData
}

var file_ring_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ring_sync_proto_goTypes = []any{
	(*RingSync)(nil),  // 0: protocol.RingSync
	(*RingRange)(nil), // 1: protocol.RingRange
}
var file_ring_sync_proto_depIdxs = []int32{
	1, // 0: protocol.RingSync.ranges:type_name -> protocol.RingRange
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ring_sync_proto_init() }
func file_ring_sync_proto_init() {
	if File_ring_sync_proto != nil {
		return
	}
	file_ring_range_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ring_sync_proto_rawDesc), len(file_ring_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ring_sync_proto_goTypes,
		DependencyIndexes: file_ring_sync_proto_depIdxs,
		MessageInfos:      file_ring_sync_proto_msgTypes,
	}.Build()
	File_ring_sync_proto = out.File
	file_ring_sync_proto_goTypes = nil
	file_ring_sync_proto_depIdxs = nil
}
