// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: ring_range.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RingRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint32                 `protobuf:"fixed32,1,opt,name=from,proto3" json:"from,omitempty"`
	To            uint32                 `protobuf:"fixed32,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RingRange) Reset() {
	*x = RingRange{}
	mi := &file_ring_range_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RingRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RingRange) ProtoMessage() {}

func (x *RingRange) ProtoReflect() protoreflect.Message {
	mi := &file_ring_range_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RingRange.ProtoReflect.Descriptor instead.
func (*RingRange) Descriptor() ([]byte, []int) {
	return file_ring_range_proto_rawDescGZIP(), []int{0}
}

func (x *RingRange) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RingRange) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_ring_range_proto protoreflect.FileDescriptor

const file_ring_range_proto_rawDesc = "" +
	"\n" +
	"\x10ring_range.proto\x12\bprotocol\"/\n" +
	"\tRingRange\x12\x12\n" +
	"\x04from\x18\x01 \x01(\aR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\aR\x02toBQ\n" +
	"\x17com.icodesoftware.protoB\x10RingRangeFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_ring_range_proto_rawDescOnce sync.Once
	file_ring_range_proto_rawDescData []byte
)

func file_ring_range_proto_rawDescGZIP() []byte {
	file_ring_range_proto_rawDescOnce.Do(func() {
		file_ring_range_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ring_range_proto_rawDesc), len(file_ring_range_proto_rawDesc)))
	})
	return file_ring_range_proto_rawDescData
}

var file_ring_range_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ring_range_proto_goTypes = []any{
	(*RingRange)(nil), // 0: protocol.RingRange
}
var file_ring_range_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ring_range_proto_init() }
func file_ring_range_proto_init() {
	if File_ring_range_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ring_range_proto_rawDesc), len(file_ring_range_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ring_range_proto_goTypes,
		DependencyIndexes: file_ring_range_proto_depIdxs,
		MessageInfos:      file_ring_range_proto_msgTypes,
	}.Build()
	File_ring_range_proto = out.File
	file_ring_range_proto_goTypes = nil
	file_ring_range_proto_depIdxs = nil
}
