// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: sub_sync.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subs          []*Subscription        `protobuf:"bytes,1,rep,name=subs,proto3" json:"subs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubSync) Reset() {
	*x = SubSync{}
	mi := &file_sub_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubSync) ProtoMessage() {}

func (x *SubSync) ProtoReflect() protoreflect.Message {
	mi := &file_sub_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubSync.ProtoReflect.Descriptor instead.
func (*SubSync) Descriptor() ([]byte, []int) {
	return file_sub_sync_proto_rawDescGZIP(), []int{0}
}

func (x *SubSync) GetSubs() []*Subscription {
	if x != nil {
		return x.Subs
	}
	return nil
}

var File_sub_sync_proto protoreflect.FileDescriptor

const file_sub_sync_proto_rawDesc = "" +
	"\n" +
	"\x0esub_sync.proto\x12\bprotocol\x1a\x12subscription.proto\"5\n" +
	"\aSubSync\x12*\n" +
	"\x04subs\x18\x01 \x03(\v2\x16.protocol.SubscriptionR\x04subsBO\n" +
	"\x17com.icodesoftware.protoB\x0eSubSyncFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_sub_sync_proto_rawDescOnce sync.Once
	file_sub_sync_proto_rawDescData []byte
)

func file_sub_sync_proto_rawDescGZIP() []byte {
	file_sub_sync_proto_rawDescOnce.Do(func() {
		file_sub_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sub_sync_proto_rawDesc), len(file_sub_sync_proto_rawDesc)))
	})
	return file_sub_sync_proto_rawDescData
}

var file_sub_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sub_sync_proto_goTypes = []any{
	(*SubSync)(nil),      // 0: protocol.SubSync
	(*Subscription)(nil), // 1: protocol.Subscription
}
var file_sub_sync_proto_depIdxs = []int32{
	1, // 0: protocol.SubSync.subs:type_name -> protocol.Subscription
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sub_sync_proto_init() }
func file_sub_sync_proto_init() {
	if File_sub_sync_proto != nil {
		return
	}
	file_subscription_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sub_sync_proto_rawDesc), len(file_sub_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sub_sync_proto_goTypes,
		DependencyIndexes: file_sub_sync_proto_depIdxs,
		MessageInfos:      file_sub_sync_proto_msgTypes,
	}.Build()
	File_sub_sync_proto = out.File
	file_sub_sync_proto_goTypes = nil
	file_sub_sync_proto_depIdxs = nil
}
