// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: vm_object.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VMObject struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Platform          string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"` // cloud platform key for AuthKey lookup (gcp, vultr, ...)
	NumberOfInstances uint32                 `protobuf:"fixed32,2,opt,name=numberOfInstances,proto3" json:"numberOfInstances,omitempty"`
	Repository        string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"` // git repo to clone and build
	Tag               string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`               // git tag / docker image tag
	Branch            string                 `protobuf:"bytes,5,opt,name=branch,proto3" json:"branch,omitempty"`         // git branch for build
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VMObject) Reset() {
	*x = VMObject{}
	mi := &file_vm_object_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMObject) ProtoMessage() {}

func (x *VMObject) ProtoReflect() protoreflect.Message {
	mi := &file_vm_object_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMObject.ProtoReflect.Descriptor instead.
func (*VMObject) Descriptor() ([]byte, []int) {
	return file_vm_object_proto_rawDescGZIP(), []int{0}
}

func (x *VMObject) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *VMObject) GetNumberOfInstances() uint32 {
	if x != nil {
		return x.NumberOfInstances
	}
	return 0
}

func (x *VMObject) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *VMObject) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VMObject) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

var File_vm_object_proto protoreflect.FileDescriptor

const file_vm_object_proto_rawDesc = "" +
	"\n" +
	"\x0fvm_object.proto\x12\bprotocol\"\x9e\x01\n" +
	"\bVMObject\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12,\n" +
	"\x11numberOfInstances\x18\x02 \x01(\aR\x11numberOfInstances\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x16\n" +
	"\x06branch\x18\x05 \x01(\tR\x06branchBP\n" +
	"\x17com.icodesoftware.protoB\x0fVMObjectFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_vm_object_proto_rawDescOnce sync.Once
	file_vm_object_proto_rawDescData []byte
)

func file_vm_object_proto_rawDescGZIP() []byte {
	file_vm_object_proto_rawDescOnce.Do(func() {
		file_vm_object_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vm_object_proto_rawDesc), len(file_vm_object_proto_rawDesc)))
	})
	return file_vm_object_proto_rawDescData
}

var file_vm_object_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vm_object_proto_goTypes = []any{
	(*VMObject)(nil), // 0: protocol.VMObject
}
var file_vm_object_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vm_object_proto_init() }
func file_vm_object_proto_init() {
	if File_vm_object_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vm_object_proto_rawDesc), len(file_vm_object_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vm_object_proto_goTypes,
		DependencyIndexes: file_vm_object_proto_depIdxs,
		MessageInfos:      file_vm_object_proto_msgTypes,
	}.Build()
	File_vm_object_proto = out.File
	file_vm_object_proto_goTypes = nil
	file_vm_object_proto_depIdxs = nil
}
