// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: vps_access.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VpsAccess struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ssh           string                 `protobuf:"bytes,1,opt,name=ssh,proto3" json:"ssh,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ApiKey        string                 `protobuf:"bytes,3,opt,name=apiKey,proto3" json:"apiKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpsAccess) Reset() {
	*x = VpsAccess{}
	mi := &file_vps_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpsAccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpsAccess) ProtoMessage() {}

func (x *VpsAccess) ProtoReflect() protoreflect.Message {
	mi := &file_vps_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpsAccess.ProtoReflect.Descriptor instead.
func (*VpsAccess) Descriptor() ([]byte, []int) {
	return file_vps_access_proto_rawDescGZIP(), []int{0}
}

func (x *VpsAccess) GetSsh() string {
	if x != nil {
		return x.Ssh
	}
	return ""
}

func (x *VpsAccess) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *VpsAccess) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

var File_vps_access_proto protoreflect.FileDescriptor

const file_vps_access_proto_rawDesc = "" +
	"\n" +
	"\x10vps_access.proto\x12\bprotocol\"I\n" +
	"\tVpsAccess\x12\x10\n" +
	"\x03ssh\x18\x01 \x01(\tR\x03ssh\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x16\n" +
	"\x06apiKey\x18\x03 \x01(\tR\x06apiKeyBQ\n" +
	"\x17com.icodesoftware.protoB\x10VpsAccessFactoryZ$gameclustering.com/internal/protocolb\x06proto3"

var (
	file_vps_access_proto_rawDescOnce sync.Once
	file_vps_access_proto_rawDescData []byte
)

func file_vps_access_proto_rawDescGZIP() []byte {
	file_vps_access_proto_rawDescOnce.Do(func() {
		file_vps_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vps_access_proto_rawDesc), len(file_vps_access_proto_rawDesc)))
	})
	return file_vps_access_proto_rawDescData
}

var file_vps_access_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vps_access_proto_goTypes = []any{
	(*VpsAccess)(nil), // 0: protocol.VpsAccess
}
var file_vps_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vps_access_proto_init() }
func file_vps_access_proto_init() {
	if File_vps_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vps_access_proto_rawDesc), len(file_vps_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vps_access_proto_goTypes,
		DependencyIndexes: file_vps_access_proto_depIdxs,
		MessageInfos:      file_vps_access_proto_msgTypes,
	}.Build()
	File_vps_access_proto = out.File
	file_vps_access_proto_goTypes = nil
	file_vps_access_proto_depIdxs = nil
}
